draw_line:
  figsize: [9,6]

  xlabel: 'Labeled samples (%)'     # x_label
  ylabel: 'Accuracy (%)'          # y_label
  xl_size: 24                     # x_label size
  yl_size: 24                     # y_label size
  title_size: 24                  # title size

  xticks: [5,10,15,20,25,30]
  yticks: null

  ax:    
    alpha: 0.05  # transparency of var
    tick_params:  # tick paras
      axis: 'both'
      labelsize: 24
    lw: 2  # line width
    markersize: 10  # marker size
  grid:                             # grid paras
    axis: 'both'
    linestyle: '--'
  legend:                           # legend paras
    fontsize: 18
    loc: 'lower right'

draw_histogram:
  figsize: [12,5]                   # [width, length] of the figure

  labels: ['1','2','3','4','5','6']   # legend of histogram
  xlabel: 'xxx'                     
  ylabel: 'Accuracy (%)'
  xl_size: 15
  yl_size: 15
  title_size: 15

  ax:
    textsize: 7                     # font size of legend
    tick_params:                    # tick paras
      axis: 'both'
      labelsize: 18
  grid:                             # grid paras
    axis: 'y'
    linestyle: '--'
  legend:                           # legend paras
    fontsize: 12
    loc: 'upper left'
  
