figsize: [12,5]                   # [width, length] of the figure

labels: ['1','2','3','4','5','6']   # legend of histogram
xlabel: 'xxx'                     
ylabel: 'Accuracy (%)'
xl_size: 15
yl_size: 15
title_size: 15

ax:
  textsize: 7                     # font size of legend
  tick_params:                    # tick paras
    axis: 'both'
    labelsize: 18
grid:                             # grid paras
  axis: 'y'
  linestyle: '--'
legend:                           # legend paras
  fontsize: 12
  loc: 'upper left'