figsize: [9,6]
cmap: 'coolwarm'  # refer to colormap of matplotlib or like cmap: ['red','green','blue']

xlabel: 'xlabel'  # x_label
ylabel: 'ylabel'  # y_label
zlabel: 'zlabel'  # z_label
xl_size: 10  # x_label size
yl_size: 10  # y_label size
zl_size: 10  # z_label size
title_size: 10  # title size

xval: [-5.0, -2.5, 0.0, 2.5, 5.0]  # x_value
yval: [-5.0, -2.5, 0.0, 2.5, 5.0]  # y_value

tick:
  x: null         # xticks
  y: null         # yticks
  z: null         # auto

tick_params:  # tick paras
  axis: 'both'
  labelsize: 10

pane_color:       # panel color, RGB
  x: [1, 0.84, 0, 1.0]   
  y: [1, 0.84, 0, 1.0]

contourf:         # draw projection
  offset: 0       # offset to z=0
  cmap: null      # color

interp2d:
  kind: 'cubic'   # interpolation type
  xnew: 30        # increase the x_value to
  ynew: 30        # increase the y_value to
